// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkripsiAppBackend.Persistence;

#nullable disable

namespace SkripsiAppBackend.Migrations
{
    [DbContext(typeof(PostgresqlApplicationDatabase))]
    partial class PostgresqlApplicationDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkripsiAppBackend.DomainModel.TrackedTeam", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text");

                    b.Property<bool>("IsUntracked")
                        .HasColumnType("boolean");

                    b.HasKey("TeamId", "ProjectId", "OrganizationName");

                    b.ToTable("TrackedTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
